<?php
// $Id: image_pager.module,v 1.3 2006/12/24 18:59:00 bjaspan Exp $

function image_pager_help($section = '') {
  switch ($section) {		  
    case 'admin/modules#description':
      return t('Dynamically switch among images with prev/next links.  Requires jquery47 module.');
  }
}

function _image_pager_add_files() {
  $path = drupal_get_path('module', 'image_pager');
  if (function_exists('module_exist')) {
    if (module_exist('jquery47')) {
      jquery47_add_js($path.'/image_pager.js');
      drupal_set_html_head
	(theme('stylesheet_import', url($path.'/image_pager.css')));
    }
  } else {
    drupal_add_css($path.'/image_pager.css');
    drupal_add_js($path.'/image_pager.js');
  }
}

function image_pager_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
  case 'list':
    return array(array('info' => t('Image Pager')));
    
  case 'view':
    _image_pager_add_files();
    return array('subject' => t('Images'),
		 'content' => theme('image_pager_block'));
    
  default:
    break;
  }
}

function theme_image_pager_block() {
  return ('<div class="image-pager">'.
	  '<form action="/">'.
	  '  <input type="hidden" name="sel" value="'.
	  str_replace('+','%20',urlencode(theme('image_pager_selector'))).
	  '" />'.
	  '</form>'.
	  '<div class="pager">'.
	  '  <a class="prev">&laquo; Prev</a>'.
	  '  <span class="count"></span>'.
	  '  <a class="next">Next &raquo;</a>'.
	  '</div>'.
	  '<div class="image"><a><img /></a></div>'.
	  '<div class="caption"></div>'.
	  '<div class="credit"></div>'.
	  '</div>');
}

function theme_image_pager_selector() {
  return '.node .content img';
}
  
?>
