<?php
// $Id: gallerix.install,v 1.3 2007/10/30 02:24:23 silviogutierrez Exp $

/**
 * Implementation of hook_install().
 */
function gallerix_install() {
  switch ($GLOBALS['db_type']) {
    case 'mysql':
    case 'mysqli':
      db_query("
        CREATE TABLE {gallerix_albums} (
        nid int unsigned NOT NULL default '0',
        path text NOT NULL,
        settings longtext,
        PRIMARY KEY  (nid)
        ) /*!40100 DEFAULT CHARACTER SET UTF8 */
        ");
        
      db_query("
        CREATE TABLE {gallerix_pictures} (
        pid int unsigned NOT NULL default '0',
        nid int unsigned NOT NULL default '0',
        path text NOT NULL,
        name text NOT NULL,
        caption text NOT NULL,
        created int unsigned NOT NULL default '0',
        votes int unsigned NOT NULL default '0',
        sort int unsigned NOT NULL default '0',
        width int unsigned NOT NULL default '0',
        height int unsigned NOT NULL default '0',        
        exif longtext,
        iptc longtext,
        original_name text,
        PRIMARY KEY  (pid),
        KEY nid (nid)
        ) /*!40100 DEFAULT CHARACTER SET UTF8 */
        ");       
      break;

    case 'pgsql':        
      db_query("
        CREATE TABLE {gallerix_albums} (
        nid int unsigned NOT NULL default '0',
        path text NOT NULL,
        settings longtext,
        PRIMARY KEY  (nid)
        )
        ");
        
      db_query("
        CREATE TABLE {gallerix_pictures} (
        pid int unsigned NOT NULL default '0',
        nid int unsigned NOT NULL default '0',
        path text NOT NULL,
        name text NOT NULL,
        caption text NOT NULL,
        created int unsigned NOT NULL default '0',
        votes int unsigned NOT NULL default '0',
        sort int unsigned NOT NULL default '0',
        width int unsigned NOT NULL default '0',
        height int unsigned NOT NULL default '0',            
        exif longtext,
        iptc longtext,
        original_name text,
        PRIMARY KEY  (pid),
        KEY nid (nid)
        )
        ");
  }
  $success = false;
  
  $path = file_directory_path() . '/gallerix';
  $success = mkdir($path);
  $success = chmod($path, 0777);
  $success = mkdir($path . '/trash');
  $success = chmod($path . '/trash', 0777); 
  $success = mkdir($path . '/repository');
  $success = chmod($path . '/repository', 0777);   
  $success = mkdir($path . '/albums');
  $success = chmod($path . '/albums', 0777);     
  
  if (!$success) {
    drupal_set_message(t('Gallerix did not install successfully. Please make sure all directories were created, with full permissions.'));
  }
  else {
    drupal_set_message(t('Gallerix installed successfully.'));
  }
}

/**
 * Implementation of hook_uninstall().
 */
function gallerix_uninstall() {
  db_query('DROP TABLE {gallerix_albums}');
  db_query('DROP TABLE {gallerix_pictures}');
  _gallerix_uninstall(file_directory_path() . '/gallerix');
}

/**
 * Recursively delete the gallerix directory.
 *
 * @author swizec@swizec.com
 */
function _gallerix_uninstall($dir) {

  if (!is_writable($dir)) {
    if (!@chmod( $dir, 0777)) {
      return FALSE;
    }
  }

  $d = dir( $dir );
  
  while (FALSE !== ($entry = $d->read())) {
    if ($entry == '.' || $entry == '..') {
      continue;
    }
    $entry = $dir . '/' . $entry;
    if (is_dir($entry)) {
    
      if (!_gallerix_uninstall($entry)) {
        return FALSE;
      }
      continue;
    }
    if (!@unlink($entry)) {
      $d->close();
      return FALSE;
    }
  }

  $d->close();

  rmdir($dir);

  return TRUE;
}

