<?php
// $Id $


/**
 * Implementation of hook_install()
 * just give a message
 */
function lightbox2_install() {
  module_invoke('content', 'clear_type_cache');
  watchdog('lightbox2', 'lightbox2 module installed');
}

/**
 * Implementation of hook_uninstall()
 */
function lightbox2_uninstall() {
  // delete the variables we created
  variable_del('lightbox2_plus');
  variable_del('lightbox2_lite');

  variable_del('lightbox2_use_alt_layout');
  variable_del('lightbox2_force_show_nav');
  variable_del('lightbox2_image_count_str');
  variable_del('lightbox2_disable_zoom');
  variable_del('lightbox2G2_filter');
  variable_del('lightbox2_disable_these_urls');

  variable_del('lightbox2_image_node');
  variable_del('lightbox2_flickr');
  variable_del('lightbox2_image_group');
  variable_del('lightbox2_node_link_text');
  variable_del('lightbox2_disable_nested_galleries');
  
  watchdog('lightbox2', 'lightbox2 module un-installed');
}

function lightbox2_update_1() {
  $ret = array();
  switch ($GLOBALS['db_type']) {
    case 'mysql':
    case 'mysqli':
      $ret[] = update_sql('UPDATE {variable} SET name="lightbox2_lite"
        WHERE name="lightbox2_plus";');
      break;

    case 'pgsql':
      $ret[] = update_sql('UPDATE {variable} SET name="lightbox2_lite"
        WHERE name="lightbox2_plus";');
      break;
  }

  return $ret;
}


